config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  root :to => 'people/coaches#show', :constraints => lambda { |request| request.env['warden'].person.type == 'Coach' }
  root :to => 'people/users#show', :constraints => lambda { |request| request.env['warden'].person.type == 'User' }
  
  devise_for :people, controllers: { sessions: 'sessions', registrations: 'people'}
  devise_scope :people do
    get     '/sign_in' => 'sessions#new'
    post    '/sign_in' => 'sessions#create'
    delete  '/sign_out' => 'sessions#destroy'
    get     '/sign_up', to: 'people#new', as: 'signup'
    post    '/sign_up', to: 'people#create'
  end

  get 'profiles/show'

  get 'profile/show'

  get 'uipages/user_ui'
  get 'uipages/employee_ui'
  get 'uipages/admin_ui'

  get 'pages/home'
  get 'pages/main_ui'

  ##
  resources "contacts", only: [:new, :create]
  get '/contact', to: 'contacts#new', as: 'contact'

  get '/about', to: 'pages#sobre', as: 'about'
  get '/exercises', to: 'pages#exercicios', as: 'exercises' 
  get '/flexao', to: 'pages#flexao', as: 'flexao' 

  get '/squat', to: 'pages#squat', as: 'squat' 
  get '/burpee', to: 'pages#burpee', as: 'burpee' 
  

  get '/gami', to: 'pages#gamification', as: 'gami'

   #formulário de criação de treino

   resources :workout_menu, only: [:show]

   resources :people, only: [:new, :create, :edit, :update] do

    resources :users do 
      member do 
        resources :conversations, only: [:create] do
            member do
                post :close
            end
          resources :messages, only: [:create]
          post 'messages', to: 'messages#create', as: 'user_messages'
        end
        get '/chat', to: 'chat#index', as: 'chat'
        get 'profile', 'setting'
      end
    end

    resources :coaches do
      member do
        resources :conversations, only: [:create] do
            member do
                post :close
            end
        resources :messages, only: [:create]
        end
        get '/chat', to: 'chat#index', as: 'chat'
        get 'users_profile', to: 'coaches#users_profile'
      end
    end
  end

  resources :users, only: [:show, :edit, :update] do
    resources :trainings, only: [:show, :end_workout]
    post 'end_workout', to: "trainings#end_workout"
    resources :diet_menu, only: [:show, :finish]
    resources :trainings,     only: [:show]
    resources :diet_menu,     only: [:show]
    resources :diseases,      only: [:update, :create, :destroy]
    resources :restrictions,  only: [:update, :create, :destroy] 
    get   'info',                       to: 'user_measures#info'
    get   'user_measures/show/:id',     to: 'user_measures#show', as: 'measures_show'
    get   'user_measures/new/:id',      to: 'user_measures#new'
    post  'user_measures',              to: 'user_measures#create'
    resources :statistic,   only: [:show]
    resources :friendships, only: [:create, :update, :destroy, :new]
    resources :rankings   , only: [:global_ranking, :local_ranking]
    get 'rankings/global_ranking',       to: 'rankings#global_ranking'
    get 'rankings/local_ranking' ,       to: 'rankings#local_ranking'

  end



  resources :coaches do
    get   'diets',              to: 'diets#show'
    post  'diets',              to: 'diets#create'
    resources :diets, only: [:show, :create]

    get   'foods',              to: 'foods#show'
    resources :foods, only: [:show, :create]

    get   'exercises',          to: 'exercises#show'
    resources :exercises, only: [:show, :create]

    get   'workouts',           to: 'workouts#new'
    resources :workouts, only: [:workouts_page, :create_do_workout, :create, :workouts_history]
    get   'workouts_page',      to: 'workouts#workouts_page'
    get   'workouts_history',   to: 'workouts#workouts_history'
    post  'workout_creations',  to: 'workouts#create_do_workout'
    post  'workout_end',        to: 'workouts#workout_score'

    get   '/diet_assign',       to: 'diet_assign#show'
    resources :diet_assign

    get   '/choose_diet',       to: 'choose_diet#show'
    post  '/choose_diet',       to: 'choose_diet#create'
    post  '/choose_diet/:id',   to: 'choose_diet#create'
    resources :choose_diet
  end


end

app/models/workout.rb
class Workout < ApplicationRecord
	belongs_to :coach
	has_many :user_do_workouts
	has_many :user, through: :user_do_workouts
	accepts_nested_attributes_for :user_do_workouts
	
	has_many :workout_composes
	has_many :exercises, through: :workout_composes
	accepts_nested_attributes_for :workout_composes
	
	validates :name, presence: true, length: {maximum: 50}
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
	before_action :authenticate_person!
	def workouts_page
		@user_workout = User.find(params[:id_user])
		@user_do_workout_id = @user_workout.id
	end

	def workouts_history
		@workouts_history = Workout.where(coach_id: current_coach.id).includes(:workout_composes,
		 :user_do_workouts)

	end	
	
	def create_do_workout
		@user_workout = User.find(params[:id_user])
		@user_do_workout_id = @user_workout.id
		@do_workout = UserDoWorkout.new(user_id: @user_do_workout_id,
		 workout_id: params[:workout_id], ended: false, score: 0)
		#debugger

		if @do_workout.save
			flash.now[:success] = "Treino enviado com sucesso!"
			#redirect_to coach_workout_creation_path
		else
			flash.now[:danger] = "Não foi possível adicionar o treino"
		end

		render 'workouts_page'
	end

	def workout_score
		@userDo = UserDoWorkout.find_by(user_id: params[:id_user], workout_id: params[:workout_id])
		@user_wkt = User.find(params[:id_user])
		if params[:save]
			current_score = @userDo.score
			new_score = params[:score]
			@userDo.update_attributes(:score => new_score)
			@user_wkt.update_attributes(:points => current_score.to_i + new_score.to_i)
			if (@userDo.save && @user_wkt.save)
				flash[:success] = "Nota enviada com sucesso!"
			end
		end
	end

	def new
		@workout = Workout.new
		@coach = Coach.find(params[:coach_id])
	end

	def create
		@workout = Workout.new(workout_params)
		@coach = Coach.find(params[:coach_id])
		if @workout.save
			redirect_to coach_workouts_path
		else
			render 'new'
		end
	end

	private
	def workout_params
		params.require(:workout).permit(:name, :coach_id,
		 :workout_composes_attributes => [:set, :repetition, :technique, :exercise_id, :workout_id])
	end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
	def user_do_workout?(user, workout)
		UserDoWorkout.find_by(user_id: user.id, workout_id: workout.workout_id).nil?
	end

	def find_workouts(coach)
		@workout_composes = []
		Workout.where(coach_id: coach.id).each do |wo|
			@workout_composes << wo.workout_composes
		end 
	end
end

app/views/workouts/new.html.erb
    <link href="/css/morris.css" rel="stylesheet">
    <link href="/css/sb-admin.css" rel="stylesheet">
    <link href="/css/training.css" rel="stylesheet">
    <link href="/css/workout_creation.css" rel="stylesheet">
    <link href="/css/profile.css", rel="stylesheet">


    <div id="wrapper">

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-sm-2"></div>
                    <div class="col-lg-8">
                        <h3>Insira os dados do treino</h3>
                        <%= simple_form_for [@coach, @workout], :html => {:class => 'form-basic' }  do |f| %>
                            <%= f.input :name, label: "Nome do treino" %>
                            <%= f.input :coach_id, :as => :hidden, :input_html => { :value => @coach.id } %>
                            <%= f.nested_fields_for :workout_composes, id: "workout_composes" do |ff| %>
                                    <%= ff.remove_nested_fields_link  %>
                                    <br>
                                    <%= ff.input :set, label: 'Número de conjuntos' %>
                                    <%= ff.input :repetition, label: 'Número de repetições' %>
                                    <%= ff.input :technique, label: 'Qual técnica' %>
                                    <%= ff.input :workout_id, :as => :hidden %>
                                    <%= ff.association :exercise, label: "Nome do Exercício", label_method: :name_exercise, value_method: :id, include_blank: false%>
                            <% end %>
                            <%= f.add_nested_fields_link :workout_composes %>
                            <br><br>
                            <%= f.button :submit, id: "create_workout" %>
                        <% end %>
                        <br><br>
                    </div>
                </div>

            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>

app/views/workouts/show.html.erb
    <link href="/css/morris.css" rel="stylesheet">
    <link href="/css/sb-admin.css" rel="stylesheet">
    <link href="/css/workout_creations.css" rel="stylesheet">
    <link href="/css/profile.css", rel="stylesheet">
    <title>SB Admin - Bootstrap Admin Template</title>

    <div id="wrapper">

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Criar treinos <small>E-xercite</small>
                        </h1>                           
                        
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">Treinos criados</h3>
                                   
                            </div>
                            <div class="panel-body">
                                
                                <div class="list-group">
                                    <table class="table table-striped">
                                      <thead>
                                        <tr>
                                          <th class='text-center'>Treino</th>
                                          <th class='text-center'>Exercício</th>
                                          <th class='text-center'>Sequências</th>
                                          <th class='text-center'>Repetições</th>
                                          <th class='text-center'>Técnica</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                        <% find_workouts(@coach) %>
                                        <% @workout_composes.each do |wo|  %>
                                         <tr>
                                            <td align='center' style="vertical-align:middle"><%= Workout.find(wo[0].workout_id).name%></td>
                                            <td align='center' style="vertical-align:middle"><%= Exercise.find(wo[0].exercise_id).name_exercise %></td>
                                            <td align='center' style="vertical-align:middle"><%= wo[0].set%></td>
                                            <td align='center' style="vertical-align:middle"><%= wo[0].repetition %></td>
                                            <td align='center' style="vertical-align:middle"><%= wo[0].technique %></td>
                                            <td align='right'>
                                                <% if user_do_workout?(@user_workout, wo[0]) %>
                                                    <%= link_to coach_workout_creations_path(workout_id: wo[0].workout_id, id_user: @user_workout.id), :method => :post do %>
                                                        <button class="button", id="create">Enviar</button>
                                                    <% end %>
                                                    <!--<%= button_to "Enviar", {action: 'create_do_workout', workout_id: wo[0].workout_id, id_user: @user_workout.id}, {class: "button", id: "create", data: {disable_with: "Enviando"}}%> -->
                                                <% else %>
                                                   <!-- <% if UserDoWorkout.find(user_id: @user_workout.id, workout_id: wo[0].workout_id).ended %>
                                                        <% button_to "Pontuar" #e deixar um seletor de pontos em escala quando clicar em pontuar %>
                                                    <% else %> -->
                                                        <%= button_to "Enviado", {},  {class: "button-disabled",disabled: true}%>
                                                    <!--<% end %> -->

                                                <% end %>
                                            </td>
                                         </tr>
                                        <% end %>
                                      </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row" align = "center">
                    <div class="col-lg-12">
                        <%= link_to coach_workouts_path do %>
                            <button class="button", id="workout-creation">Criar novo treino</button>
                        <%end%>
                    </div>
                </div>
            
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>

app/views/workouts/workouts_history.html.erb
    <link href="/css/morris.css" rel="stylesheet">
    <link href="/css/sb-admin.css" rel="stylesheet">
    <link href="/css/workout_creations.css" rel="stylesheet">
    <link href="/css/profile.css", rel="stylesheet">
    <title>SB Admin - Bootstrap Admin Template</title>

    <div id="wrapper">

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Histórico de treinos <small>E-xercite</small>
                        </h1>                           
                        
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">Treinos criados</h3>
                                   
                            </div>
                            <div class="panel-body">
                                
                                <div class="list-group">
                                    <table class="table table-striped">
                                      <thead>
                                        <tr>
                                          <th class='text-center'>Usuário ID</th>
                                          <th class='text-center'>Treino</th>
                                          <th class='text-center'>Exercício</th>
                                          <th class='text-center'>Sequências</th>
                                          <th class='text-center'>Repetições</th>
                                          <th class='text-center'>Técnica</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                        <% @workouts_history.each do |wo| %>
                                            <% for i in 0..(wo.workout_composes.length-1) %>
                                                <tr>
                                                    <td align="center" style="vertical-align:middle"><%= wo.user_do_workouts[i].user_id %></td>
                                                    <td align='center' style="vertical-align:middle"><%= wo.name%></td>
                                                    <td align='center' style="vertical-align:middle"><%= Exercise.find(wo.workout_composes[i].exercise_id).name_exercise %></td>
                                                    <td align='center' style="vertical-align:middle"><%= wo.workout_composes[i].set%></td>
                                                    <td align='center' style="vertical-align:middle"><%= wo.workout_composes[i].repetition %></td>
                                                    <td align='center' style="vertical-align:middle"><%= wo.workout_composes[i].technique %></td>
                                                    <td align='right'>
                                                        <% if user_do_workout?(User.find(wo.user_do_workouts[i].user_id), wo.workout_composes[i]) %>
                                                            <%= button_tag "Enviar", class: "button" %>
                                                        <% else %>
                                                            <%= button_tag "Enviado", class: "button-disabled"%>
                                                        <% end %>
                                                    </td>
                                                </tr>
                                            <%end%>
                                        <% end %>
                                      </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>

app/views/workouts/workouts_page.html.erb
    <link href="/css/morris.css" rel="stylesheet">
    <link href="/css/sb-admin.css" rel="stylesheet">
    <link href="/css/workout_creations.css" rel="stylesheet">
    <link href="/css/profile.css", rel="stylesheet">
    <title>SB Admin - Bootstrap Admin Template</title>

    <div id="wrapper">

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Criar treinos <small>E-xercite</small>
                        </h1>                           
                        
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">Treinos criados</h3>
                                   
                            </div>
                            <div class="panel-body">
                                
                                <div class="list-group">
                                    <table class="table table-striped">
                                      <thead>
                                        <tr>
                                          <th class='text-center'>Treino</th>
                                          <th class='text-center'>Exercício</th>
                                          <th class='text-center'>Sequências</th>
                                          <th class='text-center'>Repetições</th>
                                          <th class='text-center'>Técnica</th>
                                          <th class='text-center'>Nota</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                        <% find_workouts(current_coach) %>
                                        <% @workout_composes.each do |wo|  %>
                                         <tr>
                                            <td align='center' style="vertical-align:middle"><%= Workout.find(wo[0].workout_id).name%></td>
                                            <td align='center' style="vertical-align:middle"><%= Exercise.find(wo[0].exercise_id).name_exercise %></td>
                                            <td align='center' style="vertical-align:middle"><%= wo[0].set%></td>
                                            <td align='center' style="vertical-align:middle"><%= wo[0].repetition %></td>
                                            <td align='center' style="vertical-align:middle"><%= wo[0].technique %></td>
                                            <td align='right'>
                                                <% if user_do_workout?(@user_workout, wo[0]) %>
                                                    <%= link_to coach_workout_creations_path(workout_id: wo[0].workout_id, id_user: @user_workout.id), :method => :post do %>
                                                        <button class="button", id="create">Enviar</button>
                                                    <% end %>

                                                    <% if false %>
                                                        <%= button_to "Enviar", {action: 'create_do_workout', workout_id: wo[0].workout_id, id_user: @user_workout.id}, {class: "button", id: "create", data: {disable_with: "Enviando"}}%>
                                                    <% end %>
                                                <% else %>
                                                    <% workout_finished = UserDoWorkout.find_by(user_id: @user_workout.id, workout_id:  wo[0].workout_id)
                                                    if  (workout_finished.ended && workout_finished.score == 0)%>
                                                        <%= form_tag coach_workout_end_path(workout_id: wo[0].workout_id, id_user: @user_workout.id,:method => :post) do %>
                                                         <%= select_tag('score', options_for_select((1..10).step(1).to_a, :selected => @selected_score)) %>
                                                         <%= submit_tag "Salvar", :name => 'save' %>
                                                        <% end %>
                                                    <% else %>
                                                        <%= button_to "Enviado", {},  {class: "button-disabled",disabled: true}%>
                                                    <% end%>
                                                <% end %>
                                            </td>
                                         </tr>
                                        <% end %>
                                      </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row" align = "center">
                    <div class="col-lg-12">
                        <%= link_to coach_workouts_path do %>
                            <button class="button", id="workout-creation">Criar novo treino</button>
                        <%end%>
                    </div>
                </div>
            
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>