config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  root :to => 'people/coaches#show', :constraints => lambda { |request| request.env['warden'].person.type == 'Coach' }
  root :to => 'people/users#show', :constraints => lambda { |request| request.env['warden'].person.type == 'User' }
  
  devise_for :people, controllers: { sessions: 'sessions', registrations: 'people'}
  devise_scope :people do
    get     '/sign_in' => 'sessions#new'
    post    '/sign_in' => 'sessions#create'
    delete  '/sign_out' => 'sessions#destroy'
    get     '/sign_up', to: 'people#new', as: 'signup'
    post    '/sign_up', to: 'people#create'
  end

  get 'profiles/show'

  get 'profile/show'

  get 'uipages/user_ui'
  get 'uipages/employee_ui'
  get 'uipages/admin_ui'

  get 'pages/home'
  get 'pages/main_ui'

  ##
  resources "contacts", only: [:new, :create]
  get '/contact', to: 'contacts#new', as: 'contact'

  get '/about', to: 'pages#sobre', as: 'about'
  get '/exercises', to: 'pages#exercicios', as: 'exercises' 
  get '/flexao', to: 'pages#flexao', as: 'flexao' 

  get '/squat', to: 'pages#squat', as: 'squat' 
  get '/burpee', to: 'pages#burpee', as: 'burpee' 
  

  get '/gami', to: 'pages#gamification', as: 'gami'

   #formulário de criação de treino

   resources :workout_menu, only: [:show]

   resources :people, only: [:new, :create, :edit, :update] do

    resources :users do 
      member do 
        resources :conversations, only: [:create] do
            member do
                post :close
            end
          resources :messages, only: [:create]
          post 'messages', to: 'messages#create', as: 'user_messages'
        end
        get '/chat', to: 'chat#index', as: 'chat'
        get 'profile', 'setting'
      end
    end

    resources :coaches do
      member do
        resources :conversations, only: [:create] do
            member do
                post :close
            end
        resources :messages, only: [:create]
        end
        get '/chat', to: 'chat#index', as: 'chat'
        get 'users_profile', to: 'coaches#users_profile'
      end
    end
  end

  resources :users, only: [:show, :edit, :update] do
    resources :trainings, only: [:show, :end_workout]
    post 'end_workout', to: "trainings#end_workout"
    resources :diet_menu, only: [:show, :finish]
    resources :trainings,     only: [:show]
    resources :diet_menu,     only: [:show]
    resources :diseases,      only: [:update, :create, :destroy]
    resources :restrictions,  only: [:update, :create, :destroy] 
    get   'info',                       to: 'user_measures#info'
    get   'user_measures/show/:id',     to: 'user_measures#show', as: 'measures_show'
    get   'user_measures/new/:id',      to: 'user_measures#new'
    post  'user_measures',              to: 'user_measures#create'
    resources :statistic,   only: [:show]
    resources :friendships, only: [:create, :update, :destroy, :new]
    resources :rankings   , only: [:global_ranking, :local_ranking]
    get 'rankings/global_ranking',       to: 'rankings#global_ranking'
    get 'rankings/local_ranking' ,       to: 'rankings#local_ranking'

  end



  resources :coaches do
    get   'diets',              to: 'diets#show'
    post  'diets',              to: 'diets#create'
    resources :diets, only: [:show, :create]

    get   'foods',              to: 'foods#show'
    resources :foods, only: [:show, :create]

    get   'exercises',          to: 'exercises#show'
    resources :exercises, only: [:show, :create]

    get   'workouts',           to: 'workouts#new'
    resources :workouts, only: [:workouts_page, :create_do_workout, :create, :workouts_history]
    get   'workouts_page',      to: 'workouts#workouts_page'
    get   'workouts_history',   to: 'workouts#workouts_history'
    post  'workout_creations',  to: 'workouts#create_do_workout'
    post  'workout_end',        to: 'workouts#workout_score'

    get   '/diet_assign',       to: 'diet_assign#show'
    resources :diet_assign

    get   '/choose_diet',       to: 'choose_diet#show'
    post  '/choose_diet',       to: 'choose_diet#create'
    post  '/choose_diet/:id',   to: 'choose_diet#create'
    resources :choose_diet
  end


end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: Person
  belongs_to :recipient, foreign_key: :recipient_id, class_name: Person

  validates :sender_id, uniqueness: { scope: :recipient_id }

  scope :between, -> (sender_id, recipient_id) do
    where(sender_id: sender_id, recipient_id: recipient_id).or(
      where(sender_id: recipient_id, recipient_id: sender_id)
    )
  end

  def self.get(sender_id, recipient_id)
    conversation = between(sender_id, recipient_id).first
    return conversation if conversation.present?

    create(sender_id: sender_id, recipient_id: recipient_id)
  end

  def opposed_user(user)
    user == recipient ? sender : recipient
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_person!
  include SessionsHelper
  def create
    
    @conversation = Conversation.get(current_person.id, params[:person_id])
    add_to_conversations unless conversated?

    respond_to do |format|
      format.js
    end
  end

  def close
    @conversation = Conversation.find(params[:id])
    session[:conversations].delete(@conversation.id)
    respond_to do |format|
      format.js
    end
  end

  private

  def add_to_conversations
    session[:conversations] ||= []
    session[:conversations] << @conversation.id
  end

  def conversated?
    session[:conversations].include?(@conversation.id)
  end
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/views/conversations/_conversation.html.erb
<li>
  <div class="container">
  <div class="row">
    <div class="col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
      <div class="panel panel-default" data-conversation-id="<%= conversation.id %>">
        <div class="panel-heading">
          <%= link_to conversation.opposed_user(person).email, '', class: 'toggle-window' %>
          <%= link_to "x", close_person_conversation_path(id: conversation.id), class: "btn btn-default btn-xs pull-right", remote: true, method: :post %>
        </div>

        <div class="panel-body" style="display: none;">
          <div class="messages-list">
            <ul>
              <%= render 'conversations/conversation_content', messages: conversation.messages, person: person %>
            </ul>
          </div>
          <%= form_for conversation.messages.new, url: person_conversation_user_messages_path(person_id: current_person.id, conversation_id: conversation.id), remote: true do |f| %>
            <%= f.hidden_field :person_id, value: person.id %>
            <%= f.text_area :body, class: "form-control" %>
            <%= f.submit "Send", class: "btn btn-success" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/conversations/_conversation_content.html.erb
<% messages.each do |message| %>
  <%= render message, person: person %>
<% end %>

app/views/conversations/close.js.erb
$('#conversations-list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']").parent().remove();

app/views/conversations/create.js.erb
var conversations = $('#conversations-list');
var conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");

if (conversation.length !== 1) {
  conversations.append("<%= j(render 'conversations/conversation', conversation: @conversation, person: current_person) %>");
  conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
}

conversation.find('.panel-body').show();

var messages_list = conversation.find('.messages-list');
var height = messages_list[0].scrollHeight;
messages_list.scrollTop(height);