config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  root :to => 'people/coaches#show', :constraints => lambda { |request| request.env['warden'].person.type == 'Coach' }
  root :to => 'people/users#show', :constraints => lambda { |request| request.env['warden'].person.type == 'User' }
  
  devise_for :people, controllers: { sessions: 'sessions', registrations: 'people'}
  devise_scope :people do
    get     '/sign_in' => 'sessions#new'
    post    '/sign_in' => 'sessions#create'
    delete  '/sign_out' => 'sessions#destroy'
    get     '/sign_up', to: 'people#new', as: 'signup'
    post    '/sign_up', to: 'people#create'
  end

  get 'profiles/show'

  get 'profile/show'

  get 'uipages/user_ui'
  get 'uipages/employee_ui'
  get 'uipages/admin_ui'

  get 'pages/home'
  get 'pages/main_ui'

  ##
  resources "contacts", only: [:new, :create]
  get '/contact', to: 'contacts#new', as: 'contact'

  get '/about', to: 'pages#sobre', as: 'about'
  get '/exercises', to: 'pages#exercicios', as: 'exercises' 
  get '/flexao', to: 'pages#flexao', as: 'flexao' 

  get '/squat', to: 'pages#squat', as: 'squat' 
  get '/burpee', to: 'pages#burpee', as: 'burpee' 
  

  get '/gami', to: 'pages#gamification', as: 'gami'

   #formulário de criação de treino

   resources :workout_menu, only: [:show]

   resources :people, only: [:new, :create, :edit, :update] do

    resources :users do 
      member do 
        resources :conversations, only: [:create] do
            member do
                post :close
            end
          resources :messages, only: [:create]
          post 'messages', to: 'messages#create', as: 'user_messages'
        end
        get '/chat', to: 'chat#index', as: 'chat'
        get 'profile', 'setting'
      end
    end

    resources :coaches do
      member do
        resources :conversations, only: [:create] do
            member do
                post :close
            end
        resources :messages, only: [:create]
        end
        get '/chat', to: 'chat#index', as: 'chat'
        get 'users_profile', to: 'coaches#users_profile'
      end
    end
  end

  resources :users, only: [:show, :edit, :update] do
    resources :trainings, only: [:show, :end_workout]
    post 'end_workout', to: "trainings#end_workout"
    resources :diet_menu, only: [:show, :finish]
    resources :trainings,     only: [:show]
    resources :diet_menu,     only: [:show]
    resources :diseases,      only: [:update, :create, :destroy]
    resources :restrictions,  only: [:update, :create, :destroy] 
    get   'info',                       to: 'user_measures#info'
    get   'user_measures/show/:id',     to: 'user_measures#show', as: 'measures_show'
    get   'user_measures/new/:id',      to: 'user_measures#new'
    post  'user_measures',              to: 'user_measures#create'
    resources :statistic,   only: [:show]
    resources :friendships, only: [:create, :update, :destroy, :new]
    resources :rankings   , only: [:global_ranking, :local_ranking]
    get 'rankings/global_ranking',       to: 'rankings#global_ranking'
    get 'rankings/local_ranking' ,       to: 'rankings#local_ranking'

  end



  resources :coaches do
    get   'diets',              to: 'diets#show'
    post  'diets',              to: 'diets#create'
    resources :diets, only: [:show, :create]

    get   'foods',              to: 'foods#show'
    resources :foods, only: [:show, :create]

    get   'exercises',          to: 'exercises#show'
    resources :exercises, only: [:show, :create]

    get   'workouts',           to: 'workouts#new'
    resources :workouts, only: [:workouts_page, :create_do_workout, :create, :workouts_history]
    get   'workouts_page',      to: 'workouts#workouts_page'
    get   'workouts_history',   to: 'workouts#workouts_history'
    post  'workout_creations',  to: 'workouts#create_do_workout'
    post  'workout_end',        to: 'workouts#workout_score'

    get   '/diet_assign',       to: 'diet_assign#show'
    resources :diet_assign

    get   '/choose_diet',       to: 'choose_diet#show'
    post  '/choose_diet',       to: 'choose_diet#create'
    post  '/choose_diet/:id',   to: 'choose_diet#create'
    resources :choose_diet
  end


end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, class_name: "User"
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	before_action :authenticate_person!
	include SessionsHelper

	def new 
	end

	def create
		@friendship = current_user.friendships.build(friend_id: params[:friend_id])
		if @friendship.save
			flash.now[:success] = "Requisição de amizade enviada"
		end
		render :new
	end

	def update
		@friendship = Friendship.find_by(id: params[:id])
		@friendship.update_attribute(:accepted, "accepted")
		if @friendship.save
			flash.now[:success] = "Amizade confirmada!"
		end
		render :new
	end

	def destroy
		@friendship = Friendship.find_by(id: params[:id])
		@friendship.destroy
		redirect_to person_user_path(id: current_user.id, person_id: current_user.person_id)
	end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/new.html.erb
    <link href="/css/morris.css" rel="stylesheet">
    <link href="/css/sb-admin.css" rel="stylesheet">
    <link href="/css/workout_creations.css" rel="stylesheet">
    <link href="/css/profile.css", rel="stylesheet">
    <title>SB Admin - Bootstrap Admin Template</title>

    <div id="wrapper">

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Lista de Amizades <small>E-xercite</small>
                        </h1>                           
                        
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">Amizades</h3>
                                   
                            </div>
                            <div class="panel-body">
                                
                                <div class="list-group">
                                    <table class="table table-striped">
                                      <thead>
                                        <tr>
                                          <th class='text-center'>Foto</th>
                                          <th class='text-center'>Nome</th>
                                          <th class='text-center'>Idade</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                        <% current_user.friends.each do |friend|  %>
                                         <tr>
                                            <td align='center' style="vertical-align:middle"><%= image_tag(friend.avatar_url, height: "52", class: "img-circle")%></td>
                                            <td align='center' style="vertical-align:middle"><%= friend.person.name %></td>
                                            <td align='center' style="vertical-align:middle"><%= friend.person.age %></td>
                                            <td align='right'>
                                                <%= link_to user_friendship_path(id: Friendship.where('(friend_id = :id AND user_id = :user_id) OR (friend_id = :user_id AND user_id = :id)', id: friend.id, user_id: current_user.id)[0].id), method: "delete" do %>
                                                    <button class='btn btn-danger',
                                                     id = "<%="remove-friend-#{friend.id}"%>">Remover</button>
                                                <% end %>
                                            </td>
                                         </tr>
                                        <% end %>
                                      </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="panel-heading">
                                <h3 class="panel-title">Solicitações de amizades</h3>
                                   
                            </div>
                            <div class="panel-body">
                                
                                <div class="list-group">
                                    <table class="table table-striped">
                                      <thead>
                                        <tr>
                                          <th class='text-center'>Foto</th>
                                          <th class='text-center'>Nome</th>
                                          <th class='text-center'>Idade</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                        <% current_user.pending.each do |request| %>
                                         <tr>
                                            <td align='center' style="vertical-align:middle"><%= image_tag(request.avatar_url, height: "52", class: "img-circle")%></td>
                                            <td align='center' style="vertical-align:middle"><%= request.person.name %></td>
                                            <td align='center' style="vertical-align:middle"><%= request.person.age %></td>
                                            <td align='right'>
                                                <% friendship = (Friendship.find_by(friend_id: request.id, user_id: current_user.id) || Friendship.find_by(friend_id: current_user.id, user_id: request.id)) %>

                                                <% if Friendship.find(friendship.id).friend_id == current_user.id %>
                                                  <%= link_to user_friendship_path(friend_id: friendship.friend_id, user_id: friendship.user_id, id: friendship.id), method: "put" do %>
                                                      <button class='btn btn-success', 
                                                      id = "<%="accept-friend-#{request.id}"%>">Aceitar</button>
                                                  <% end %>

                                                  <%= link_to user_friendship_path(friend_id: friendship.friend_id, user_id: friendship.user_id, id: friendship.id), method: :delete do %>
                                                    <button class='btn btn-warning', 
                                                    id = "<%="refuse-friend-#{request.id}"%>">Recusar</button>
                                                  <% end %>

                                                <% else %>
                                                  <%= link_to user_friendship_path(id: friendship.id, user_id: friendship.user_id), method: "delete" do %>
                                                    <button class='btn btn-danger',
                                                     id = "<%="remove-friend-#{request.id}"%>">Remover</button>
                                                  <% end %>  
                                                <% end %> 
                                            </td>
                                         </tr>
                                        <% end %>
                                      </tbody>
                                    </table>
                                </div>
                            </div>

                            <div class="panel-heading">
                                <h3 class="panel-title">Pessoas não adicionados</h3>
                                   
                            </div>
                            <div class="panel-body">
                                
                                <div class="list-group">
                                    <table class="table table-striped">
                                      <thead>
                                        <tr>
                                          <th class='text-center'>Foto</th>
                                          <th class='text-center'>Nome</th>
                                          <th class='text-center'>Idade</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                        <% User.where.not(id: current_user.id).each do |user| %>
                                         <% next unless Friendship.where('(friend_id = :id AND user_id = :user_id) OR (friend_id = :user_id AND user_id = :id)', id: user.id, user_id: current_user.id).empty?  %>
                                         <tr>
                                            <td align='center' style="vertical-align:middle"><%= image_tag(user.avatar_url, height: "52", class: "img-circle")%></td>
                                            <td align='center' style="vertical-align:middle"><%= user.person.name %></td>
                                            <td align='center' style="vertical-align:middle"><%= user.person.age %></td>
                                            <td align='right'>
                                                <%= link_to user_friendships_path(friend_id: user.id), method: "post" do %>
                                                    <button class='btn btn-success'
                                                    id = "<%="add-friend-#{user.id}"%>">Solicitar</button>
                                                <% end %>   
                                            </td>
                                         </tr>
                                        <% end %>
                                      </tbody>
                                    </table>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

                
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>